import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <Suspense fallback={<>Loading</>}>
          <Toaster position="bottom-right" />
          <StoreProvider>
            {children}
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
